set.seed(11808901)
load(file="~/Desktop/Lung cancer/lrisk/other/nhis2002_09/cpd.RData")

load(file="~/Desktop/Lung cancer/lrisk/other/lifeyearsgained/cleaned.nhis97_01.RData")
source(file="~/Desktop/Lung cancer/lrisk/prog/lifeyearsgained/nhis_imputation.y2016m11d06.R")
save(nhis,file="~/Desktop/Lung cancer/lrisk/other/lifeyearsgained/nhis.imputed.1.RData")
load(file="~/Desktop/Lung cancer/lrisk/other/lifeyearsgained/cleaned.nhis97_01.RData")
source(file="~/Desktop/Lung cancer/lrisk/prog/lifeyearsgained/nhis_imputation.y2016m11d06.R")
save(nhis,file="~/Desktop/Lung cancer/lrisk/other/lifeyearsgained/nhis.imputed.2.RData")
load(file="~/Desktop/Lung cancer/lrisk/other/lifeyearsgained/cleaned.nhis97_01.RData")
source(file="~/Desktop/Lung cancer/lrisk/prog/lifeyearsgained/nhis_imputation.y2016m11d06.R")
save(nhis,file="~/Desktop/Lung cancer/lrisk/other/lifeyearsgained/nhis.imputed.3.RData")
load(file="~/Desktop/Lung cancer/lrisk/other/lifeyearsgained/cleaned.nhis97_01.RData")
source(file="~/Desktop/Lung cancer/lrisk/prog/lifeyearsgained/nhis_imputation.y2016m11d06.R")
save(nhis,file="~/Desktop/Lung cancer/lrisk/other/lifeyearsgained/nhis.imputed.4.RData")
load(file="~/Desktop/Lung cancer/lrisk/other/lifeyearsgained/cleaned.nhis97_01.RData")
source(file="~/Desktop/Lung cancer/lrisk/prog/lifeyearsgained/nhis_imputation.y2016m11d06.R")
save(nhis,file="~/Desktop/Lung cancer/lrisk/other/lifeyearsgained/nhis.imputed.5.RData")
